module.exports = [
    {   id:1,
        name: "USA",
        continent: "North America",
        population: 325000000,
        language: "English",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/USA_orthographic.svg/220px-USA_orthographic.svg.png",
        review: "Better than you'd think if just watch the news"
    },
    {   id:2,
        name: "China",
        continent: "Asia",
        population: 1378000000,
        language: "Mandarin",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/People%27s_Republic_of_China_%28orthographic_projection%29.svg/220px-People%27s_Republic_of_China_%28orthographic_projection%29.svg.png",
        review: "Unbelieavably huge and best food ever"
    },
    {   id:3,
        name: "Japan",
        continent: "Asia",
        population: 127000000,
        language: "Japanese",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Japan_%28orthographic_projection%29.svg/220px-Japan_%28orthographic_projection%29.svg.png",
        review: "Super expensive, my taxi was like 200 bucks"
    },
    {   id:4,
        name: "Mexico",
        continent: "North America",
        population: 127000000,
        language: "Spanish",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/MEX_orthographic.svg/220px-MEX_orthographic.svg.png",
        review: "the food is mad dank"
    },
    {   id:5,
        name: "Germany",
        continent: "Europe",
        population: 83000000,
        language: "German",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/EU-Germany_%28orthographic_projection%29.svg/220px-EU-Germany_%28orthographic_projection%29.svg.png",
        review: "Can't believe the Nazis ruled this place a couple generations ago"
    },
    {   id:6,
        name: "Nigeria",
        continent: "Africa",
        population: 186000000,
        language: "Yoruba",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Nigeria_%28orthographic_projection%29.svg/250px-Nigeria_%28orthographic_projection%29.svg.png",
        review: "Africa is a growing continent and Nigeria is leading the way"
    },
    {   id:7,
        name: "Brazil",
        continent: "South America",
        population: 208000000,
        language: "Portuguese",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/BRA_orthographic.svg/250px-BRA_orthographic.svg.png",
        review: "I'm scared of the Zika virus"
    },
    {   id:8,
        name: "France",
        continent: "Europe",
        population: 70000000,
        language: "French",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/EU-France_%28orthographic_projection%29.svg/220px-EU-France_%28orthographic_projection%29.svg.png",
        review: "lots of crossants"
    },
    {   id:9,
        name: "Chile",
        continent: "South America",
        population: 18000000,
        language: "Spanish",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/CHL_orthographic.svg/220px-CHL_orthographic.svg.png",
        review: "crazy earthquakes"
    },
    {   id:10,
        name: "Croatia",
        continent: "Europe",
        population: 4000000,
        language: "Croation",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/EU-Croatia.svg/250px-EU-Croatia.svg.png",
        review: "cool name for a Country"
    }]